site_name: Bio-Structure Hub
repo_url: https://github.com/ssciwr/BioStructureHub/



#=======    Theme Settings   =====
theme:
  name: material
  logo: images/Logoleiste_SSC_4c.png
  favicon: images/favicon.png
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode



    # Dark mode
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
 
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes # removes empty index from navigation
    - navigation.top
    - navigation.tracking
    #- toc.integrate


#=======    Website Navigation settings   =====
nav:
  - Home: index.md
  - Who we are: 
    - about.md
    - projects.md
    - cite.md
    - News:
      - blog/index.md
  - What we offer: 
    - services/service.md
    - services/collab.md
    - services/teaching.md
    - resources/methods.md
    - resources/learning.md
  - Tutorials: 
    - tutorials/tutorial_AF_bwVisu.md 
    - tutorials/tutorial_Bindcraft_bwVisu.md
    - tutorials/tutorial_Boltz_bwVisu.md
    - tutorials/tutorial_Boltzgen_bwVisu.md
    - tutorials/tutorial_RFDiffusion_bwVisu.md
  - Contact: contact.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.snippets:
      base_path: 'docs/'


plugins:
  - blog:
      archive: true
      archive_toc: false
      authors: false
      blog_toc: true
  - search
  - callouts