# This is a basic workflow to help you get started with Actions

name: CI
  
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_and_doc:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, 3.13]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Getting repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Pre-cache matplotlib font (cross-platform)
      run: |
        python -c "import os; os.environ['MPLBACKEND']='Agg'; import matplotlib.pyplot"

    - name: Run AlphaFold3  Alignment notebook
      run: |
        python -m pytest --nbval notebooks/AFold_Alignment_CPU.ipynb tests/afold_alignment_output.py
        
    - name: Run AlphaFold3 Inference notebook
      run: |
        python -m pytest --nbval notebooks/AFold_Diffusion_GPU.ipynb tests/afold_diffusion_output.py

    - name: Run AlphaFold3 Analysis notebook
      run: |  
        python -m pytest tests/afold_prepare_analysis.py
        python -m pytest --nbval notebooks/AFold_Confidence_Levels.ipynb

    - name: Run Bindcraft notebook
      run: |  
        python -m pytest --nbval  notebooks/bindcraft.ipynb tests/bindcraft_output.py

    - name: Run Boltz Inference notebook
      run: |  
        python -m pytest --nbval notebooks/boltz_input.ipynb tests/boltz_output.py

    - name: Run Boltz Analysis notebook
      run: |  
        python -m pytest tests/boltz_prepare_analysis.py
        python -m pytest --nbval notebooks/boltz_confidence_levels.ipynb
        
    - name: Run Boltzgen
      run: |  
        python -m pytest --nbval notebooks/boltzgen.ipynb tests/boltzgen_output.py

    - name: Run RFDiffusion
      run: |  
        python -m pytest --nbval  notebooks/RFDiffusion.ipynb tests/rfdiffusion_output.py

